### ISSUE TITLE
Deployment link of github pages is not working ?

### ISSUE THREAD

**Issue by rrchaubey** [pranavanand24/Artificial-Intelligence-And-Data-Science-Pro#1]

**Comment by DaveSaah** [comment]
I made a fork of the repo and got the github pages working. But it only shows the README content.

Screenshot of the setting:
![image](https://user-images.githubusercontent.com/53381103/177559448-9112e246-8014-4686-8d41-ce824f8e3df5.png)


In the pages tab under settings:

- Select the main (or master) branch
- Choose the root directory and save

Here is how it looks like: https://davesaah.github.io/Artificial-Intelligence-And-Data-Science-Pro/

I hope this helps
